spring:
  application:
    name: HelloClient
  redis:
    port: 6379
    host: xxxx
    password: xxxxx
  profiles:
    active:

server:
  port: 7000

redis:
  config:
    enable: true

#xx:
#  name: redis-client

#eureka:
#  password: password
#  client:
#    serviceUrl:
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#
#
#endpoints:
#  restart:
#    enabled: true
