spring:
  application:
    name: HelloClient
  redis:
    port: 6379
    host: www.ecndata.cn
    password: redismm6436

server:
  port: 7000

#xx:
#  name: redis-client

#eureka:
#  password: password
#  client:
#    serviceUrl:
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#
#
#endpoints:
#  restart:
#    enabled: true
